language: objective-c
xcode_workspace: ColorMapView.xcworkspace
xcode_scheme: ColorMapExample
xcode_sdk: iphonesimulator
xcode_scheme:
 - ColorMapView
 - ColorMapExample
 - "Podspec Lint"

before_install:
 - rm Podfile.lock
 - sudo easy_install cpp-coveralls
 - mkdir -p /Users/travis/Library/Application\ Support/iPhone\ Simulator/7.1/Library/Caches/RFCachingDirecory
 - export LC_ALL="en_US.UTF-8"
 - sudo pip install PyYAML
 - pod install

after_success:
 - ./coveralls.rb --extension m --extension mm -v