language: objective-c
xcode_workspace: ColorMapView.xcworkspace
xcode_sdk: iphonesimulator
#xcode_scheme:
# - ColorMapView
# - ColorMapExample
# - "Podspec Lint"

script:
 - xctool -workspace ColorMapView.xcworkspace -scheme 'ColorMapView' \
build test -sdk iphonesimulator GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES

before_install:
 - rm Podfile.lock
 - sudo easy_install cpp-coveralls
 - mkdir -p /Users/travis/Library/Application\ Support/iPhone\ Simulator/7.1/Library/Caches/RFCachingDirecory
 - export LC_ALL="en_US.UTF-8"
 - sudo pip install PyYAML
 - pod install

after_success:
 - bash <(curl -s https://codecov.io/bash)